version: '3.7'
services:
  node-client:
    labels: 
      - traefik.tcp.routers.roncaspotclient.tls=true
      - traefik.tcp.routers.roncaspotclient.entrypoints=https
      - traefik.tcp.routers.roncaspotclient.tls.passthrough=true
      - traefik.tcp.routers.roncaspotclient.rule=HostSNI(`roncaspot.github.io`)
      - traefik.tcp.services.roncaspotclient.loadbalancer.server.port=443
    networks:
      local-shared-net:
        aliases: 
          - "roncaspot.github.io"
          - "roncaspot.hyperweb2.com"


