version: '3.7'
services:
  node-client:
    command: npm run start
    restart: unless-stopped
    image: roncaspot.github.io
    build:
      context: .
    volumes:
      - type: bind
        source: .
        target: /usr/src/service
      # restore node_modules
      - /usr/src/service/node_modules
    working_dir: /usr/src/service
    user: node
    environment:
      - CHOKIDAR_USEPOLLING=true
      - PORT=443
      - HTTPS=true
    networks:
      - local-shared-net
    ports:
      - ${DOCKER_NODE_CLIENT_PORT:-44003}:443
    expose:
      - "80"
      - "443"
volumes:
  node_modules:
networks:
  local-shared-net:
    external: true
