name: Github Pages Pipeline
on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:

env:
  NODE_VERSION: 14
jobs:
  #===========================
  #
  #  DOC PIPELINE
  #
  #============================
  build:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache global npm
        uses: actions/cache@v2
        env:
          cache-name: cache-gh-pages-global-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Cache local node_modules
        uses: actions/cache@v2
        env:
          cache-name: cache-gh-pages-modules
        with:
          path: 'node_modules'
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
      - name: Build app
        run: |
          sudo apt-get update
          sudo apt-get install -y libgbm1
          git config --global user.name "Yehonal"
          git config --global user.email "yehonal.azeroth@gmail.com"
          git remote set-url origin https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/roncaspot/roncaspot.github.io.git
          npm install
          npm run build
          npm run deploy

